### ISSUE TITLE
default.json usage in config directory

### ISSUE THREAD

**Issue by simofacc** [SystangoTechnologies/Hapiness#1]
Hi,

I am currently evaluating your boilerplate and I was wondering how is the default.json file inside the config folder being used, if it is being used at all, or what was its initial scope.

**Comment by vpatidar-systango** [comment]
Hi simofacc,

Thanks for using hapiness.  

default.json file is used to defined various constants that are used in project and the purpose is to keep them all in single place.

For example let say we are using Status Codes in our project and we want to kept them in one place and for that we define Status Codes in default.json
```
{
 "STATUS_CODES": {
        "SUCCESS": 200
}
}
```

And to retrieve anywhere in project we can used below line of code.
```
const statusCodes = require('config').get('STATUS_CODES');
statusCodes.SUCCESS will return 200.
```
You can also define messages that are used in project and many more.

I hope this will clear.
